# -*- coding: utf-8 -*-
"""streamlit_aidan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYXNWjDWC3_vCII7X5WzwMng5JCkovMo
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv("Advertising_F.csv")

st.title("Advertising Effectiveness Dashboard – Aidan")
st.sidebar.header("Filters")

x_var = st.sidebar.selectbox("X-Axis", ['TV', 'radio', 'newspaper'])
y_var = st.sidebar.selectbox("Y-Axis", ['sales'])

fig = px.scatter(df, x=x_var, y=y_var, trendline='ols')
st.plotly_chart(fig)

st.write("### Data Frame")
st.dataframe(df)

# Optional map if columns exist
if {'latitude', 'longitude', 'City'}.issubset(df.columns):
    st.title("Sales by City Map")
    fig = px.scatter_mapbox(df, lat='latitude', lon='longitude',
                            color='sales', size='TV', hover_name='City')
    fig.update_layout(mapbox_style="carto-positron")
    st.plotly_chart(fig)