# -*- coding: utf-8 -*-
"""streamlit_aidan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJDhv3CdM1DDTjblqFoBONI07LakgqYw
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  !pip install streamlit
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv("/content/Advertising_F.csv")
df.head()

st.title("Advertising Effectiveness Daashboard_Aidan")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X-Axis", ['TV', 'radio', 'newspaper'])
y_var=st.sidebar.selectbox("Y-Axis", ['sales'])

fig=px.scatter(df, x=x_var, y=y_var,trendline='ols')
st.plotly_chart(fig)

st.write('### Data Frame')
st.dataframe(df)

st.title("I'm the MAP!!!!!")
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',color='sales',size='TV',hover_name'City')

fig.update_layout(mapbox_style="carto-positron")
st.plotly_chart(fig)